# Generated by Django 5.2.4 on 2025-07-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_file', models.FileField(upload_to='encrypted_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField(help_text='Size of the encrypted file in bytes')),
                ('is_encrypted', models.BooleanField(default=True)),
                ('salt', models.BinaryField(max_length=16)),
                ('nonce', models.BinaryField(max_length=16)),
            ],
        ),
    ]
