# Generated by Django 5.2.4 on 2025-07-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_encryptedfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for encryption/decryption', max_length=255, null=True),
        ),
    ]
