# Generated by Django 5.2.4 on 2025-07-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_encryptedfile_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='decrypted_temp_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
