# Generated by Django 5.2.4 on 2025-07-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_encryptedfile_decrypted_temp_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DECRYPTING', 'Decrypting'), ('DECRYPTED', 'Decrypted')], default='PENDING', max_length=50),
        ),
    ]
