# Generated by Django 5.2.4 on 2025-07-19 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_encryptedfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='original_file_size',
            field=models.BigIntegerField(blank=True, help_text='Size of the original file in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='encrypted_file',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_files/'),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='nonce',
            field=models.BinaryField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='salt',
            field=models.BinaryField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='dashboard.directory')),
            ],
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.directory'),
        ),
    ]
