# Generated by Django 5.2.4 on 2025-12-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_encryptedfile_original_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='mark_deleted',
            field=models.BooleanField(default=False, help_text='Mark this directory for deletion without removing it immediately'),
        ),
        migrations.AddField(
            model_name='directory',
            name='mark_deleted_date',
            field=models.DateTimeField(blank=True, help_text='Date when the directory was marked for deletion', null=True),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='mark_deleted',
            field=models.BooleanField(default=False, help_text='Mark this file for deletion without removing it immediately'),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='mark_deleted_date',
            field=models.DateTimeField(blank=True, help_text='Date when the file was marked for deletion', null=True),
        ),
    ]
